version: '3.7'
services:
  micro_email:
    build:
      args:
        user: raycon
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on: 
    - redis_micro_email
    - queue
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - microemail

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8005:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d
    networks:
      - microemail
  
  # queue
  queue:
    build:
      args:
        user: raycon
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - redis_micro_email
    networks:
      - microemail

  # redis
  redis_micro_email:
    image: redis:latest
    networks:
      - microemail

networks:
  microemail:
    driver: bridge
